language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO="django>=1.7,<1.8" CMS="django-cms>=3.1,<3.3"
  - DJANGO="django>=1.8,<1.9" CMS="django-cms>=3.1"
  - TOXENV=lint

matrix:
  exclude:
  - python: "3.5"
    env: DJANGO="django>=1.7,<1.8"
install:
  - "pip install setuptools -U"
  - "pip install $DJANGO $CMS"
script:
  - make travis
after_success:
  - coveralls
